//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIP_EthernetIP_Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIP_EthernetIP_Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of {0} is too small to hold the {1} data. Size of {0} should be {2} bytes..
        /// </summary>
        internal static string BufferTooSmallInvalidDataException {
            get {
                return ResourceManager.GetString("BufferTooSmallInvalidDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object doesn&apos;t support deserialization..
        /// </summary>
        internal static string DeserializationNotSupportedInvalidOperationException {
            get {
                return ResourceManager.GetString("DeserializationNotSupportedInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization into this object is not allowed..
        /// </summary>
        internal static string DoNotDeserializeInvalidOperationException {
            get {
                return ResourceManager.GetString("DoNotDeserializeInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nAn error occurred.\n\tStatus code:\t{0:X}.\n\tHighest supported protocol version:\t{1}. \nSession not created..
        /// </summary>
        internal static string ErrorCodeUnsupportedProtocolVersionException {
            get {
                return ResourceManager.GetString("ErrorCodeUnsupportedProtocolVersionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}. {1}.
        /// </summary>
        internal static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nAn error occurred.\n\tStatus code:\t{0:X}.\nSession not created..
        /// </summary>
        internal static string GeneralIOException {
            get {
                return ResourceManager.GetString("GeneralIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command specific data returned wasn&apos;t in the correct format..
        /// </summary>
        internal static string IncorrectCommandSpecificDataFormatException {
            get {
                return ResourceManager.GetString("IncorrectCommandSpecificDataFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data received was of an invalid length..
        /// </summary>
        internal static string InvalidDataLengthFormatException {
            get {
                return ResourceManager.GetString("InvalidDataLengthFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header data is invalid or not in the correct format..
        /// </summary>
        internal static string InvalidHeaderFormatException {
            get {
                return ResourceManager.GetString("InvalidHeaderFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a host name as the first argument..
        /// </summary>
        internal static string MalformedCommandLineArgs {
            get {
                return ResourceManager.GetString("MalformedCommandLineArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must be of type {1}..
        /// </summary>
        internal static string MustBeEnumArugmentException {
            get {
                return ResourceManager.GetString("MustBeEnumArugmentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket Exception: {0}. {1}.
        /// </summary>
        internal static string SendReceiveSocketException {
            get {
                return ResourceManager.GetString("SendReceiveSocketException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object doesn&apos;t support serialization..
        /// </summary>
        internal static string SerializationNotSupportedInvalidOperationException {
            get {
                return ResourceManager.GetString("SerializationNotSupportedInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read data from the server..
        /// </summary>
        internal static string UnableToReadDataIOException {
            get {
                return ResourceManager.GetString("UnableToReadDataIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send data to the server..
        /// </summary>
        internal static string UnableToSendDataIOException {
            get {
                return ResourceManager.GetString("UnableToSendDataIOException", resourceCulture);
            }
        }
    }
}
